# Generated by Django 4.2.16 on 2025-02-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_subjectnotes_subjectcalculator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcalculator',
            name='calculator_url',
        ),
        migrations.AddField(
            model_name='subjectcalculator',
            name='html_template',
            field=models.CharField(default='exit', help_text='Путь к HTML-шаблону или URL', max_length=255),
            preserve_default=False,
        ),
    ]
