# Generated by Django 4.2.16 on 2025-02-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_subjectcalculator_calculator_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('path_to_template', models.CharField(help_text='Например: calculator/index.html', max_length=255)),
            ],
        ),
    ]
