# Generated by Django 4.2.16 on 2025-02-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
