# Generated by Django 4.2.16 on 2025-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_delete_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcalculator',
            name='html_template',
            field=models.CharField(help_text='Введите путь к шаблону, например: calculator/math_list.html', max_length=255),
        ),
    ]
