# Generated by Django 4.2.16 on 2025-02-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_subjectcalculator_html_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcalculator',
            name='html_template',
            field=models.CharField(help_text='Путь к HTML-шаблону или URL', max_length=255),
        ),
    ]
