# Generated by Django 4.2.16 on 2025-02-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_subjectcalculator_html_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='svg_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
