# Generated by Django 4.2.16 on 2025-03-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_lesson_svg_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='answerselection',
            options={'ordering': ['question'], 'verbose_name': 'Выбранный ответ', 'verbose_name_plural': 'Выбранные ответы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['topic', 'title'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['lesson'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='subjectcalculator',
            options={'verbose_name': 'Калькулятор', 'verbose_name_plural': 'Калькуляторы'},
        ),
        migrations.AlterModelOptions(
            name='subjectnotes',
            options={'verbose_name': 'Конспект', 'verbose_name_plural': 'Конспекты'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['subject', 'name'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='answerselection',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_selections', to='courses.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answerselection',
            name='selected_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_answers', to='courses.answer', verbose_name='Выбранный ответ'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='allow_latex',
            field=models.BooleanField(default=True, verbose_name='Разрешить LaTeX'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Объяснение урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='svg_content',
            field=models.TextField(blank=True, null=True, verbose_name='SVG-код'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Объяснение ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subjects/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='subjectcalculator',
            name='html_template',
            field=models.CharField(help_text='Путь к HTML-шаблону или URL', max_length=255, verbose_name='HTML-шаблон'),
        ),
        migrations.AlterField(
            model_name='subjectcalculator',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subjectnotes',
            name='notes_content',
            field=models.TextField(blank=True, null=True, verbose_name='Конспект'),
        ),
        migrations.AlterField(
            model_name='subjectnotes',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topics/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название темы'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.subject', verbose_name='Предмет'),
        ),
    ]
