# Generated by Django 4.2.16 on 2025-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_answer_options_alter_answerselection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='board_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные доски'),
        ),
    ]
