# Generated by Django 4.2.16 on 2025-03-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lesson_board_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='board_data',
            field=models.TextField(blank=True, null=True, verbose_name='Данные доски'),
        ),
    ]
