# Generated by Django 4.2.16 on 2025-03-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_lesson_board_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='board_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
