# Generated by Django 4.2.16 on 2025-03-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_lesson_board_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='allow_latex',
            field=models.BooleanField(default=True, help_text='Если отмечено, LaTeX будет обрабатываться во всех текстовых полях урока', verbose_name='Разрешить LaTeX во всех полях'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='board_data',
            field=models.JSONField(blank=True, help_text='JSON с сохраненными рисунками, может содержать LaTeX-подписи', null=True, verbose_name='Данные доски'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text='Полная поддержка LaTeX. Используйте $$...$$ для формул и $...$ для встроенных выражений', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='explanation',
            field=models.TextField(blank=True, help_text='Поддержка LaTeX. Используйте стандартные математические окружения', null=True, verbose_name='Объяснение урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='svg_content',
            field=models.TextField(blank=True, help_text='SVG с возможностью вставки LaTeX через <text> элементы', null=True, verbose_name='SVG-код'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='Можно использовать базовые LaTeX-команды: $формула$ для встроенных формул, $$формула$$ для вынесенных', max_length=255, verbose_name='Название урока'),
        ),
    ]
