# Generated by Django 4.2.16 on 2025-02-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_mathentry_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_template', models.CharField(help_text='Введите путь к шаблону, например: calculator/math_list.html', max_length=255)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculator.subject')),
            ],
        ),
    ]
