# Generated by Django 4.2.16 on 2025-02-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_subject_subjectcalculator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcalculator',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectCalculator',
        ),
    ]
