# Generated by Django 4.2.16 on 2025-02-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_remove_subjectcalculator_subject_delete_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=50)),
                ('value1', models.FloatField()),
                ('value2', models.FloatField(blank=True, null=True)),
                ('result', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
